repos:
 # Ruff for Python formatting and linting
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.7.0
   hooks:
     - id: ruff
       name: Ruff Linter 
       args: ["--fix"] # Automatically fix issues
       files: ^app/ # Only app folder
       stages: [pre-commit]
     - id: ruff-format
       name: Ruff Formatter 
       files: ^app/ # Only app folder
       stages: [pre-commit]