[project]
name = "proof-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pre-commit>=2.21.0",
    "python-docx>=1.1.0",
    "streamlit>=1.23.1",
]
